Data Preprocessing

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Loading Dataset

In [2]:
data = pd.read_csv("/content/drive/MyDrive/Churn_Modelling.csv")

In [3]:
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
x=data.iloc[:,3:13]

In [5]:
y= data.iloc[:,13]

In [6]:
print(x)

      CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1
1             608     Spain  Female   41       1   83807.86              1
2             502    France  Female   42       8  159660.80              3
3             699    France  Female   39       1       0.00              2
4             850     Spain  Female   43       2  125510.82              1
...           ...       ...     ...  ...     ...        ...            ...
9995          771    France    Male   39       5       0.00              2
9996          516    France    Male   35      10   57369.61              1
9997          709    France  Female   36       7       0.00              1
9998          772   Germany    Male   42       3   75075.31              2
9999          792    France  Female   28       4  130142.79              1

      HasCrCard  IsActiveMember  EstimatedSalary
0             1               1        101348.88
1             0               1        112542.58
2             1               0        113931.57
3             0               0         93826.63
4             1               1         79084.10
...         ...             ...              ...
9995          1               0         96270.64
9996          1               1        101699.77
9997          0               1         42085.58
9998          1               0         92888.52
9999          1               0         38190.78

[10000 rows x 10 columns]

In [7]:
print(y)

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

Label Encoding

In [9]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_x_2=LabelEncoder()

In [12]:
x.iloc[:, 2] = labelencoder_x_2.fit_transform(x.iloc[:, 2])

<ipython-input-12-92975d6ea503>:1: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  x.iloc[:, 2] = labelencoder_x_2.fit_transform(x.iloc[:, 2])

In [13]:
print(x)

      CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France       0   42       2       0.00              1
1             608     Spain       0   41       1   83807.86              1
2             502    France       0   42       8  159660.80              3
3             699    France       0   39       1       0.00              2
4             850     Spain       0   43       2  125510.82              1
...           ...       ...     ...  ...     ...        ...            ...
9995          771    France       1   39       5       0.00              2
9996          516    France       1   35      10   57369.61              1
9997          709    France       0   36       7       0.00              1
9998          772   Germany       1   42       3   75075.31              2
9999          792    France       0   28       4  130142.79              1

      HasCrCard  IsActiveMember  EstimatedSalary
0             1               1        101348.88
1             0               1        112542.58
2             1               0        113931.57
3             0               0         93826.63
4             1               1         79084.10
...         ...             ...              ...
9995          1               0         96270.64
9996          1               1        101699.77
9997          0               1         42085.58
9998          1               0         92888.52
9999          1               0         38190.78

[10000 rows x 10 columns]

one hot encoding

In [14]:
from sklearn.compose import ColumnTransformer

In [26]:
ct = ColumnTransformer([('ohe',OneHotEncoder(),[1])],remainder='passthrough')

In [27]:
from sklearn.preprocessing import OneHotEncoder
x = np.array(ct.fit_transform(x),dtype =np.str)

<ipython-input-27-e950f5b4a9e7>:2: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(ct.fit_transform(x),dtype =np.str)

splitting

In [29]:
from sklearn.model_selection import train_test_split

In [83]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

feature scaling

In [84]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train =sc.fit_transform(x_train)
x_test =sc.fit_transform(x_test)

In [85]:
import pandas as pd
print(x_train)

[[ 1.00150113 -0.57946723 -0.57638802 ...  0.64920267  0.97481699
   1.36766974]
 [-0.99850112  1.72572313 -0.57638802 ...  0.64920267  0.97481699
   1.6612541 ]
 [-0.99850112 -0.57946723  1.73494238 ...  0.64920267 -1.02583358
  -0.25280688]
 ...
 [ 1.00150113 -0.57946723 -0.57638802 ... -1.54035103 -1.02583358
  -0.1427649 ]
 [ 1.00150113 -0.57946723 -0.57638802 ...  0.64920267 -1.02583358
  -0.05082558]
 [-0.99850112  1.72572313 -0.57638802 ...  0.64920267  0.97481699
  -0.81456811]]

In [86]:
pd.DataFrame(x_train)

,0,1,2,3,4,5,6,7,8,9,10,11
0,1.001501,-0.579467,-0.576388,0.356500,0.913248,-0.655786,0.345680,-1.218471,0.808436,0.649203,0.974817,1.367670
1,-0.998501,1.725723,-0.576388,-0.203898,0.913248,0.294938,-0.348369,0.696838,0.808436,0.649203,0.974817,1.661254
2,-0.998501,-0.579467,1.734942,-0.961472,0.913248,-1.416365,-0.695393,0.618629,-0.916688,0.649203,-1.025834,-0.252807
3,1.001501,-0.579467,-0.576388,-0.940717,-1.094993,-1.131148,1.386753,0.953212,-0.916688,0.649203,-1.025834,0.915393
4,1.001501,-0.579467,-0.576388,-1.397337,0.913248,1.625953,1.386753,1.057449,-0.916688,-1.540351,-1.025834,-1.059600
...,...,...,...,...,...,...,...,...,...,...,...,...
7995,1.001501,-0.579467,-0.576388,1.207474,0.913248,1.435808,1.039728,-0.102301,-0.916688,0.649203,0.974817,-0.539860
7996,1.001501,-0.579467,-0.576388,0.314989,-1.094993,1.816097,-1.389442,-1.218471,-0.916688,0.649203,0.974817,-1.733882
7997,1.001501,-0.579467,-0.576388,0.865009,-1.094993,-0.085351,-1.389442,-1.218471,2.533560,-1.540351,-1.025834,-0.142765
7998,1.001501,-0.579467,-0.576388,0.159323,0.913248,0.390011,1.039728,1.827259,-0.916688,0.649203,-1.025834,-0.050826
7999,-0.998501,1.725723,-0.576388,0.470655,0.913248,1.150590,-1.389442,1.149720,-0.916688,0.649203,0.974817,-0.814568

Building ANN

In [88]:
#from tensorflow.keras.models import Sequential
from keras.models import Sequential
from keras.layers import Dense
classifier = Sequential()
classifier.add(Dense(units=6,kernel_initializer='uniform',activation = 'relu',input_dim=12))

adding Hidden Layer

In [89]:
classifier.add(Dense(units=6,kernel_initializer='uniform',activation = 'relu'))

Output layer

In [90]:

classifier.add(Dense(units=1,kernel_initializer='uniform',activation = 'sigmoid'))

compiling the ANN

In [91]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy',metrics=['accuracy'])
classifier.fit(x_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
800/800 [==============================] - 2s 2ms/step - loss: 0.5092 - accuracy: 0.7943
Epoch 2/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4354 - accuracy: 0.7945
Epoch 3/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4304 - accuracy: 0.7945
Epoch 4/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4259 - accuracy: 0.7945
Epoch 5/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4222 - accuracy: 0.8116
Epoch 6/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4189 - accuracy: 0.8256
Epoch 7/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4172 - accuracy: 0.8304
Epoch 8/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4154 - accuracy: 0.8305
Epoch 9/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4140 - accuracy: 0.8319
Epoch 10/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4128 - accuracy: 0.8334
Epoch 11/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4117 - accuracy: 0.8335
Epoch 12/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4109 - accuracy: 0.8339
Epoch 13/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4102 - accuracy: 0.8339
Epoch 14/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4095 - accuracy: 0.8349
Epoch 15/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4090 - accuracy: 0.8346
Epoch 16/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4083 - accuracy: 0.8346
Epoch 17/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4081 - accuracy: 0.8349
Epoch 18/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4071 - accuracy: 0.8353
Epoch 19/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4071 - accuracy: 0.8355
Epoch 20/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4066 - accuracy: 0.8357
Epoch 21/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4060 - accuracy: 0.8356
Epoch 22/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4060 - accuracy: 0.8364
Epoch 23/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4057 - accuracy: 0.8336
Epoch 24/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4051 - accuracy: 0.8357
Epoch 25/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4053 - accuracy: 0.8363
Epoch 26/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4047 - accuracy: 0.8360
Epoch 27/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4046 - accuracy: 0.8366
Epoch 28/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4045 - accuracy: 0.8353
Epoch 29/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4044 - accuracy: 0.8351
Epoch 30/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4044 - accuracy: 0.8381
Epoch 31/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4040 - accuracy: 0.8361
Epoch 32/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4041 - accuracy: 0.8369
Epoch 33/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4036 - accuracy: 0.8366
Epoch 34/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4041 - accuracy: 0.8359
Epoch 35/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4036 - accuracy: 0.8367
Epoch 36/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4033 - accuracy: 0.8354
Epoch 37/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4037 - accuracy: 0.8363
Epoch 38/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4035 - accuracy: 0.8357
Epoch 39/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4030 - accuracy: 0.8360
Epoch 40/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4035 - accuracy: 0.8363
Epoch 41/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4029 - accuracy: 0.8360
Epoch 42/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4032 - accuracy: 0.8371
Epoch 43/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4030 - accuracy: 0.8365
Epoch 44/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4031 - accuracy: 0.8363
Epoch 45/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4025 - accuracy: 0.8370
Epoch 46/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4027 - accuracy: 0.8353
Epoch 47/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4028 - accuracy: 0.8357
Epoch 48/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4023 - accuracy: 0.8359
Epoch 49/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4025 - accuracy: 0.8342
Epoch 50/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4026 - accuracy: 0.8357
Epoch 51/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4027 - accuracy: 0.8370
Epoch 52/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4027 - accuracy: 0.8356
Epoch 53/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4024 - accuracy: 0.8363
Epoch 54/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4025 - accuracy: 0.8356
Epoch 55/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4024 - accuracy: 0.8360
Epoch 56/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4023 - accuracy: 0.8347
Epoch 57/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4024 - accuracy: 0.8350
Epoch 58/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4024 - accuracy: 0.8353
Epoch 59/100
800/800 [==============================] - 3s 4ms/step - loss: 0.4026 - accuracy: 0.8351
Epoch 60/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4022 - accuracy: 0.8347
Epoch 61/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4022 - accuracy: 0.8359
Epoch 62/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4023 - accuracy: 0.8356
Epoch 63/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4019 - accuracy: 0.8359
Epoch 64/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4020 - accuracy: 0.8357
Epoch 65/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4021 - accuracy: 0.8359
Epoch 66/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4019 - accuracy: 0.8356
Epoch 67/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4021 - accuracy: 0.8370
Epoch 68/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4018 - accuracy: 0.8356
Epoch 69/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4025 - accuracy: 0.8357
Epoch 70/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4016 - accuracy: 0.8369
Epoch 71/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4022 - accuracy: 0.8367
Epoch 72/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4018 - accuracy: 0.8345
Epoch 73/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4018 - accuracy: 0.8365
Epoch 74/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4017 - accuracy: 0.8370
Epoch 75/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4015 - accuracy: 0.8346
Epoch 76/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4017 - accuracy: 0.8350
Epoch 77/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4016 - accuracy: 0.8364
Epoch 78/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4016 - accuracy: 0.8363
Epoch 79/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4020 - accuracy: 0.8375
Epoch 80/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4018 - accuracy: 0.8357
Epoch 81/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4016 - accuracy: 0.8378
Epoch 82/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4017 - accuracy: 0.8361
Epoch 83/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4017 - accuracy: 0.8357
Epoch 84/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4016 - accuracy: 0.8349
Epoch 85/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4016 - accuracy: 0.8366
Epoch 86/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4016 - accuracy: 0.8369
Epoch 87/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4017 - accuracy: 0.8374
Epoch 88/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4019 - accuracy: 0.8360
Epoch 89/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4017 - accuracy: 0.8366
Epoch 90/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4015 - accuracy: 0.8350
Epoch 91/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4014 - accuracy: 0.8393
Epoch 92/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4018 - accuracy: 0.8369
Epoch 93/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4017 - accuracy: 0.8366
Epoch 94/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4008 - accuracy: 0.8360
Epoch 95/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4014 - accuracy: 0.8355
Epoch 96/100
800/800 [==============================] - 2s 3ms/step - loss: 0.4013 - accuracy: 0.8347
Epoch 97/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4016 - accuracy: 0.8366
Epoch 98/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4015 - accuracy: 0.8371
Epoch 99/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4016 - accuracy: 0.8365
Epoch 100/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4015 - accuracy: 0.8366

In [92]:
y_pred =classifier.predict(x_test)
y_pred=(y_pred>0.5)
print(y_pred)

63/63 [==============================] - 0s 1ms/step
[[False]
 [False]
 [False]
 ...
 [False]
 [False]
 [False]]

In [93]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[1556   51]
 [ 265  128]]

In [94]:
accuracy_score(y_test,y_pred)

0.842